/*
 * SendinBlue API
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@sendinblue.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sibApi;

import sibModel.Body;
import sibModel.Body1;
import sibModel.ErrorModel;
import java.io.File;
import sibModel.FileData;
import sibModel.Note;
import sibModel.NoteData;
import sibModel.Task;
import sibModel.TaskTypes;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CrmApi
 */
@Ignore
public class CrmApiTest {

    private final CrmApi api = new CrmApi();

    
    /**
     * Get file details
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void crmFilesIdDataGetTest() throws Exception {
        String id = null;
        FileData response = api.crmFilesIdDataGet(id);

        // TODO: test validations
    }
    
    /**
     * Delete a file
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void crmFilesIdDeleteTest() throws Exception {
        String id = null;
        api.crmFilesIdDelete(id);

        // TODO: test validations
    }
    
    /**
     * Download a file
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void crmFilesIdGetTest() throws Exception {
        String id = null;
        api.crmFilesIdGet(id);

        // TODO: test validations
    }
    
    /**
     * Upload a file
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void crmFilesPostTest() throws Exception {
        File file = null;
        List<String> dealsIds = null;
        FileData response = api.crmFilesPost(file, dealsIds);

        // TODO: test validations
    }
    
    /**
     * Delete a note
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void crmNotesIdDeleteTest() throws Exception {
        String id = null;
        api.crmNotesIdDelete(id);

        // TODO: test validations
    }
    
    /**
     * Get a note
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void crmNotesIdGetTest() throws Exception {
        String id = null;
        Note response = api.crmNotesIdGet(id);

        // TODO: test validations
    }
    
    /**
     * Update a note
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void crmNotesIdPatchTest() throws Exception {
        String id = null;
        NoteData body = null;
        Note response = api.crmNotesIdPatch(id, body);

        // TODO: test validations
    }
    
    /**
     * Create a note
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void crmNotesPostTest() throws Exception {
        NoteData body = null;
        Note response = api.crmNotesPost(body);

        // TODO: test validations
    }
    
    /**
     * Delete a task
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void crmTasksIdDeleteTest() throws Exception {
        String id = null;
        api.crmTasksIdDelete(id);

        // TODO: test validations
    }
    
    /**
     * Get a task
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void crmTasksIdGetTest() throws Exception {
        String id = null;
        Task response = api.crmTasksIdGet(id);

        // TODO: test validations
    }
    
    /**
     * Update a task
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void crmTasksIdPatchTest() throws Exception {
        String id = null;
        Body1 body = null;
        Task response = api.crmTasksIdPatch(id, body);

        // TODO: test validations
    }
    
    /**
     * Create a task
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void crmTasksPostTest() throws Exception {
        Body body = null;
        Task response = api.crmTasksPost(body);

        // TODO: test validations
    }
    
    /**
     * Get all task types
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void crmTasktypesGetTest() throws Exception {
        TaskTypes response = api.crmTasktypesGet();

        // TODO: test validations
    }
    
}
