/*
 * SendinBlue API
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@sendinblue.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sibApi;

import sendinblue.ApiException;
import sibModel.ErrorModel;
import java.io.File;
import sibModel.FileData;
import sibModel.FileDownloadableLink;
import sibModel.FileList;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FilesApi
 */
@Ignore
public class FilesApiTest {

    private final FilesApi api = new FilesApi();

    
    /**
     * Get all files
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void crmFilesGetTest() throws ApiException {
        String entity = null;
        String entityIds = null;
        Integer dateFrom = null;
        Integer dateTo = null;
        Long offset = null;
        Long limit = null;
        String sort = null;
        FileList response = api.crmFilesGet(entity, entityIds, dateFrom, dateTo, offset, limit, sort);

        // TODO: test validations
    }
    
    /**
     * Get file details
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void crmFilesIdDataGetTest() throws ApiException {
        String id = null;
        FileData response = api.crmFilesIdDataGet(id);

        // TODO: test validations
    }
    
    /**
     * Delete a file
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void crmFilesIdDeleteTest() throws ApiException {
        String id = null;
        api.crmFilesIdDelete(id);

        // TODO: test validations
    }
    
    /**
     * Download a file
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void crmFilesIdGetTest() throws ApiException {
        String id = null;
        FileDownloadableLink response = api.crmFilesIdGet(id);

        // TODO: test validations
    }
    
    /**
     * Upload a file
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void crmFilesPostTest() throws ApiException {
        File file = null;
        String dealId = null;
        Long contactId = null;
        String companyId = null;
        FileData response = api.crmFilesPost(file, dealId, contactId, companyId);

        // TODO: test validations
    }
    
}
