/*
 * SendinBlue API
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@sendinblue.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sibModel;

import org.apache.commons.lang3.ObjectUtils;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Body8
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-02-28T15:16:18.937+05:30")
public class Body8 {
  @SerializedName("visitorId")
  private String visitorId = null;

  @SerializedName("text")
  private String text = null;

  @SerializedName("agentId")
  private String agentId = null;

  @SerializedName("receivedFrom")
  private String receivedFrom = null;

  @SerializedName("agentEmail")
  private String agentEmail = null;

  @SerializedName("agentName")
  private String agentName = null;

  public Body8 visitorId(String visitorId) {
    this.visitorId = visitorId;
    return this;
  }

   /**
   * visitor’s ID received &lt;a href&#x3D;\&quot;https://developers.sendinblue.com/docs/conversations-webhooks\&quot;&gt;from a webhook&lt;/a&gt; or generated by you to &lt;a href&#x3D;\&quot;https://developers.sendinblue.com/docs/customize-the-widget#identifying-existing-users\&quot;&gt;bind existing user account to Conversations&lt;/a&gt;
   * @return visitorId
  **/
  @ApiModelProperty(example = "kZMvWhf8npAu3H6qd57w2Hv6nh6rnxvg", required = true, value = "visitor’s ID received <a href=\"https://developers.sendinblue.com/docs/conversations-webhooks\">from a webhook</a> or generated by you to <a href=\"https://developers.sendinblue.com/docs/customize-the-widget#identifying-existing-users\">bind existing user account to Conversations</a>")
  public String getVisitorId() {
    return visitorId;
  }

  public void setVisitorId(String visitorId) {
    this.visitorId = visitorId;
  }

  public Body8 text(String text) {
    this.text = text;
    return this;
  }

   /**
   * message text
   * @return text
  **/
  @ApiModelProperty(example = "Hello! How can I help you?", required = true, value = "message text")
  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }

  public Body8 agentId(String agentId) {
    this.agentId = agentId;
    return this;
  }

   /**
   * agent ID. It can be found on agent’s page or received &lt;a href&#x3D;\&quot;https://developers.sendinblue.com/docs/conversations-webhooks\&quot;&gt;from a webhook&lt;/a&gt;. Alternatively, you can use &#x60;agentEmail&#x60; + &#x60;agentName&#x60; + &#x60;receivedFrom&#x60; instead (all 3 fields required).
   * @return agentId
  **/
  @ApiModelProperty(example = "d9nKoegKSjmCtyK78", value = "agent ID. It can be found on agent’s page or received <a href=\"https://developers.sendinblue.com/docs/conversations-webhooks\">from a webhook</a>. Alternatively, you can use `agentEmail` + `agentName` + `receivedFrom` instead (all 3 fields required).")
  public String getAgentId() {
    return agentId;
  }

  public void setAgentId(String agentId) {
    this.agentId = agentId;
  }

  public Body8 receivedFrom(String receivedFrom) {
    this.receivedFrom = receivedFrom;
    return this;
  }

   /**
   * mark your messages to distinguish messages created by you from the others.
   * @return receivedFrom
  **/
  @ApiModelProperty(example = "SuperAwesomeHelpdesk", value = "mark your messages to distinguish messages created by you from the others.")
  public String getReceivedFrom() {
    return receivedFrom;
  }

  public void setReceivedFrom(String receivedFrom) {
    this.receivedFrom = receivedFrom;
  }

  public Body8 agentEmail(String agentEmail) {
    this.agentEmail = agentEmail;
    return this;
  }

   /**
   * agent email. When sending messages from a standalone system, it’s hard to maintain a 1-to-1 relationship between the users of both systems. In this case, an agent can be specified by their email address.
   * @return agentEmail
  **/
  @ApiModelProperty(example = "liz@getwear.com", value = "agent email. When sending messages from a standalone system, it’s hard to maintain a 1-to-1 relationship between the users of both systems. In this case, an agent can be specified by their email address.")
  public String getAgentEmail() {
    return agentEmail;
  }

  public void setAgentEmail(String agentEmail) {
    this.agentEmail = agentEmail;
  }

  public Body8 agentName(String agentName) {
    this.agentName = agentName;
    return this;
  }

   /**
   * agent name
   * @return agentName
  **/
  @ApiModelProperty(example = "Liz", value = "agent name")
  public String getAgentName() {
    return agentName;
  }

  public void setAgentName(String agentName) {
    this.agentName = agentName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    Body8 body8 = (Body8) o;
    return ObjectUtils.equals(this.visitorId, body8.visitorId) &&
    ObjectUtils.equals(this.text, body8.text) &&
    ObjectUtils.equals(this.agentId, body8.agentId) &&
    ObjectUtils.equals(this.receivedFrom, body8.receivedFrom) &&
    ObjectUtils.equals(this.agentEmail, body8.agentEmail) &&
    ObjectUtils.equals(this.agentName, body8.agentName);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(visitorId, text, agentId, receivedFrom, agentEmail, agentName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body8 {\n");
    
    sb.append("    visitorId: ").append(toIndentedString(visitorId)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    agentId: ").append(toIndentedString(agentId)).append("\n");
    sb.append("    receivedFrom: ").append(toIndentedString(receivedFrom)).append("\n");
    sb.append("    agentEmail: ").append(toIndentedString(agentEmail)).append("\n");
    sb.append("    agentName: ").append(toIndentedString(agentName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

