/*
 * SendinBlue API
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@sendinblue.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sibModel;

import org.apache.commons.lang3.ObjectUtils;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Company Details
 */
@ApiModel(description = "Company Details")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-02-28T15:16:18.937+05:30")
public class Company {
  @SerializedName("id")
  private String id = null;

  @SerializedName("attributes")
  private Object attributes = null;

  @SerializedName("linkedContactsIds")
  private List<Integer> linkedContactsIds = null;

  @SerializedName("linkedDealsIds")
  private List<String> linkedDealsIds = null;

  public Company id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Unique company id
   * @return id
  **/
  @ApiModelProperty(example = "629475917295261d9b1f4403", value = "Unique company id")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Company attributes(Object attributes) {
    this.attributes = attributes;
    return this;
  }

   /**
   * Company attributes with values
   * @return attributes
  **/
  @ApiModelProperty(example = "{\"created_at\":\"2022-01-13T19:04:24.376+05:30\",\"domain\":\"xyz\",\"last_updated_at\":\"2022-04-01T18:47:48.283+05:30\",\"name\":\"text\",\"number_of_contacts\":0,\"owner\":\"62260474111b1101704a9d85\",\"owner_assign_date\":\"2022-04-01T18:21:13.379+05:30\",\"phone_number\":8171844192,\"revenue\":10}", value = "Company attributes with values")
  public Object getAttributes() {
    return attributes;
  }

  public void setAttributes(Object attributes) {
    this.attributes = attributes;
  }

  public Company linkedContactsIds(List<Integer> linkedContactsIds) {
    this.linkedContactsIds = linkedContactsIds;
    return this;
  }

  public Company addLinkedContactsIdsItem(Integer linkedContactsIdsItem) {
    if (this.linkedContactsIds == null) {
      this.linkedContactsIds = new ArrayList<Integer>();
    }
    this.linkedContactsIds.add(linkedContactsIdsItem);
    return this;
  }

   /**
   * Contact ids for contacts linked to this company
   * @return linkedContactsIds
  **/
  @ApiModelProperty(example = "[1,2,3]", value = "Contact ids for contacts linked to this company")
  public List<Integer> getLinkedContactsIds() {
    return linkedContactsIds;
  }

  public void setLinkedContactsIds(List<Integer> linkedContactsIds) {
    this.linkedContactsIds = linkedContactsIds;
  }

  public Company linkedDealsIds(List<String> linkedDealsIds) {
    this.linkedDealsIds = linkedDealsIds;
    return this;
  }

  public Company addLinkedDealsIdsItem(String linkedDealsIdsItem) {
    if (this.linkedDealsIds == null) {
      this.linkedDealsIds = new ArrayList<String>();
    }
    this.linkedDealsIds.add(linkedDealsIdsItem);
    return this;
  }

   /**
   * Deals ids for companies linked to this company
   * @return linkedDealsIds
  **/
  @ApiModelProperty(example = "[\"61a5ce58c5d4795761045990\",\"61a5ce58c5d4795761045991\",\"61a5ce58c5d4795761045992\"]", value = "Deals ids for companies linked to this company")
  public List<String> getLinkedDealsIds() {
    return linkedDealsIds;
  }

  public void setLinkedDealsIds(List<String> linkedDealsIds) {
    this.linkedDealsIds = linkedDealsIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    Company company = (Company) o;
    return ObjectUtils.equals(this.id, company.id) &&
    ObjectUtils.equals(this.attributes, company.attributes) &&
    ObjectUtils.equals(this.linkedContactsIds, company.linkedContactsIds) &&
    ObjectUtils.equals(this.linkedDealsIds, company.linkedDealsIds);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(id, attributes, linkedContactsIds, linkedDealsIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Company {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    linkedContactsIds: ").append(toIndentedString(linkedContactsIds)).append("\n");
    sb.append("    linkedDealsIds: ").append(toIndentedString(linkedDealsIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

