/*
 * SendinBlue API
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@sendinblue.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sibModel;

import org.apache.commons.lang3.ObjectUtils;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * CreateUpdateCategory
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-02-28T15:16:18.937+05:30")
public class CreateUpdateCategory {
  @SerializedName("id")
  private String id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("url")
  private String url = null;

  @SerializedName("updateEnabled")
  private Boolean updateEnabled = false;

  public CreateUpdateCategory id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Unique Category ID as saved in the shop 
   * @return id
  **/
  @ApiModelProperty(example = "CAT123", required = true, value = "Unique Category ID as saved in the shop ")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public CreateUpdateCategory name(String name) {
    this.name = name;
    return this;
  }

   /**
   * **Mandatory in case of creation**. Name of the Category, as displayed in the shop 
   * @return name
  **/
  @ApiModelProperty(example = "Electronics", value = "**Mandatory in case of creation**. Name of the Category, as displayed in the shop ")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CreateUpdateCategory url(String url) {
    this.url = url;
    return this;
  }

   /**
   * URL to the category
   * @return url
  **/
  @ApiModelProperty(example = "http://mydomain.com/category/electronics", value = "URL to the category")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public CreateUpdateCategory updateEnabled(Boolean updateEnabled) {
    this.updateEnabled = updateEnabled;
    return this;
  }

   /**
   * Facilitate to update the existing category in the same request (updateEnabled &#x3D; true)
   * @return updateEnabled
  **/
  @ApiModelProperty(example = "false", value = "Facilitate to update the existing category in the same request (updateEnabled = true)")
  public Boolean isUpdateEnabled() {
    return updateEnabled;
  }

  public void setUpdateEnabled(Boolean updateEnabled) {
    this.updateEnabled = updateEnabled;
  }


  @Override
  public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    CreateUpdateCategory createUpdateCategory = (CreateUpdateCategory) o;
    return ObjectUtils.equals(this.id, createUpdateCategory.id) &&
    ObjectUtils.equals(this.name, createUpdateCategory.name) &&
    ObjectUtils.equals(this.url, createUpdateCategory.url) &&
    ObjectUtils.equals(this.updateEnabled, createUpdateCategory.updateEnabled);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(id, name, url, updateEnabled);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateUpdateCategory {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    updateEnabled: ").append(toIndentedString(updateEnabled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

