/*
 * SendinBlue API
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@sendinblue.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sibModel;

import org.apache.commons.lang3.ObjectUtils;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Statistics about the clicked links
 */
@ApiModel(description = "Statistics about the clicked links")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-02-15T11:12:00.535+05:30")
public class GetExtendedCampaignStatsLinksStats {
  @SerializedName("nbClick")
  private Long nbClick = null;

  public GetExtendedCampaignStatsLinksStats nbClick(Long nbClick) {
    this.nbClick = nbClick;
    return this;
  }

   /**
   * Number of clicks for the link
   * @return nbClick
  **/
  @ApiModelProperty(example = "80", required = true, value = "Number of clicks for the link")
  public Long getNbClick() {
    return nbClick;
  }

  public void setNbClick(Long nbClick) {
    this.nbClick = nbClick;
  }


  @Override
  public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    GetExtendedCampaignStatsLinksStats getExtendedCampaignStatsLinksStats = (GetExtendedCampaignStatsLinksStats) o;
    return ObjectUtils.equals(this.nbClick, getExtendedCampaignStatsLinksStats.nbClick);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(nbClick);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetExtendedCampaignStatsLinksStats {\n");
    
    sb.append("    nbClick: ").append(toIndentedString(nbClick)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

