/*
 * SendinBlue API
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@sendinblue.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sibModel;

import org.apache.commons.lang3.ObjectUtils;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * Details for the Products in an order.
 */
@ApiModel(description = "Details for the Products in an order.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-02-28T15:16:18.937+05:30")
public class OrderProducts {
  @SerializedName("productId")
  private String productId = null;

  @SerializedName("quantity")
  private BigDecimal quantity = null;

  @SerializedName("variantId")
  private String variantId = null;

  @SerializedName("price")
  private BigDecimal price = null;

  public OrderProducts productId(String productId) {
    this.productId = productId;
    return this;
  }

   /**
   * ID of the product.
   * @return productId
  **/
  @ApiModelProperty(example = "P1", required = true, value = "ID of the product.")
  public String getProductId() {
    return productId;
  }

  public void setProductId(String productId) {
    this.productId = productId;
  }

  public OrderProducts quantity(BigDecimal quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * How many pieces of the product the visitor has added to the cart.
   * @return quantity
  **/
  @ApiModelProperty(example = "10.0", required = true, value = "How many pieces of the product the visitor has added to the cart.")
  public BigDecimal getQuantity() {
    return quantity;
  }

  public void setQuantity(BigDecimal quantity) {
    this.quantity = quantity;
  }

  public OrderProducts variantId(String variantId) {
    this.variantId = variantId;
    return this;
  }

   /**
   * Product ID of the red color shirts.
   * @return variantId
  **/
  @ApiModelProperty(example = "P100", value = "Product ID of the red color shirts.")
  public String getVariantId() {
    return variantId;
  }

  public void setVariantId(String variantId) {
    this.variantId = variantId;
  }

  public OrderProducts price(BigDecimal price) {
    this.price = price;
    return this;
  }

   /**
   * The price of a unit of product
   * @return price
  **/
  @ApiModelProperty(example = "99.99", required = true, value = "The price of a unit of product")
  public BigDecimal getPrice() {
    return price;
  }

  public void setPrice(BigDecimal price) {
    this.price = price;
  }


  @Override
  public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    OrderProducts orderProducts = (OrderProducts) o;
    return ObjectUtils.equals(this.productId, orderProducts.productId) &&
    ObjectUtils.equals(this.quantity, orderProducts.quantity) &&
    ObjectUtils.equals(this.variantId, orderProducts.variantId) &&
    ObjectUtils.equals(this.price, orderProducts.price);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(productId, quantity, variantId, price);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderProducts {\n");
    
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    variantId: ").append(toIndentedString(variantId)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

