/*
 * SendinBlue API
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@sendinblue.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sibModel;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import sibModel.SubAccountDetailsResponsePlanInfoCreditsEmails;

/**
 * Sub-account messaging quota details
 */
@ApiModel(description = "Sub-account messaging quota details")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-03-02T23:12:13.151+05:30")
public class SubAccountDetailsResponsePlanInfoCredits {
  @SerializedName("sms")
  private Long sms = null;

  @SerializedName("emails")
  private SubAccountDetailsResponsePlanInfoCreditsEmails emails = null;

  public SubAccountDetailsResponsePlanInfoCredits sms(Long sms) {
    this.sms = sms;
    return this;
  }

   /**
   * Sms quota of the sub-account
   * @return sms
  **/
  @ApiModelProperty(value = "Sms quota of the sub-account")
  public Long getSms() {
    return sms;
  }

  public void setSms(Long sms) {
    this.sms = sms;
  }

  public SubAccountDetailsResponsePlanInfoCredits emails(SubAccountDetailsResponsePlanInfoCreditsEmails emails) {
    this.emails = emails;
    return this;
  }

   /**
   * Get emails
   * @return emails
  **/
  @ApiModelProperty(value = "")
  public SubAccountDetailsResponsePlanInfoCreditsEmails getEmails() {
    return emails;
  }

  public void setEmails(SubAccountDetailsResponsePlanInfoCreditsEmails emails) {
    this.emails = emails;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubAccountDetailsResponsePlanInfoCredits subAccountDetailsResponsePlanInfoCredits = (SubAccountDetailsResponsePlanInfoCredits) o;
    return Objects.equals(this.sms, subAccountDetailsResponsePlanInfoCredits.sms) &&
        Objects.equals(this.emails, subAccountDetailsResponsePlanInfoCredits.emails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sms, emails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubAccountDetailsResponsePlanInfoCredits {\n");
    
    sb.append("    sms: ").append(toIndentedString(sms)).append("\n");
    sb.append("    emails: ").append(toIndentedString(emails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

